### PR TITLE
[Vue] migrate angularjs code to vue

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Changes:
* Migrate editcustomtranslations directive to Vue component.

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
Works for me locally, but I think the tests haven't passed in a while.

**Review by AltamashShaikh — COMMENTED** [review]
@diosmosis Looks good.
Can you please check if testcases are not failing due to this change and may be we have to update few UI screenshot

**Review by AltamashShaikh — APPROVED** [review]

**Comment by diosmosis** [comment]
@AltamashShaikh updated.

**Comment by AltamashShaikh** [comment]
@diosmosis Awesome :tada:

**Comment by sgiehl** [comment]
Just a small note on this one: The UI screenshots changed a bit more than expected. The Custom Reports part is no longer included. Guess that is the case, as the checkout of the plugin fails on travis due to an authentication issue with the github token.
@AltamashShaikh might be good to change/fix that again.

**Comment by diosmosis** [comment]
Apologies, should have taken a closer look.

**Comment by AltamashShaikh** [comment]
@tsteur How to fix the authentication issue here ?

**Comment by tsteur** [comment]
@AltamashShaikh can you check if it works now?

**Comment by AltamashShaikh** [comment]
@tsteur Worked :+1:

**Comment by AltamashShaikh** [comment]
@sgiehl @diosmosis Fixed via #24

**Pull request merged**
